services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - ./client/.env
    ports:
      - "8080:80"
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    networks:
      - app-network
    # depends_on:
    #   - database

  # database:
  #   image: mysql:latest
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: your_database_name
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
